/* Setting up PROD DB */
CREATE DATABASE prod;
USE prod;

CREATE TABLE parking(
PARKING_NUMBER INT PRIMARY KEY,
AVAILABLE bool NOT NULL,
TYPE VARCHAR(10) NOT NULL
);

CREATE TABLE ticket(
 ID INT PRIMARY KEY AUTO_INCREMENT,
 PARKING_NUMBER INT NOT NULL,
 VEHICLE_REG_NUMBER VARCHAR(10) NOT NULL,
 PRICE double,
 IN_TIME DATETIME NOT NULL,
 OUT_TIME DATETIME,
 FOREIGN KEY (PARKING_NUMBER)
 REFERENCES parking(PARKING_NUMBER));

INSERT INTO parking(PARKING_NUMBER,AVAILABLE,TYPE) VALUES(1,true,'CAR');
INSERT INTO parking(PARKING_NUMBER,AVAILABLE,TYPE) VALUES(2,true,'CAR');
INSERT INTO parking(PARKING_NUMBER,AVAILABLE,TYPE) VALUES(3,true,'CAR');
INSERT INTO parking(PARKING_NUMBER,AVAILABLE,TYPE) VALUES(4,true,'BIKE');
INSERT INTO parking(PARKING_NUMBER,AVAILABLE,TYPE) VALUES(5,true,'BIKE');


ALTER TABLE ticket ADD COLUMN discount TINYINT(1) DEFAULT 0;
commit;

/* Setting up TEST DB */
CREATE DATABASE test;
USE test;

CREATE TABLE parking(
PARKING_NUMBER int PRIMARY KEY,
AVAILABLE bool NOT NULL,
TYPE varchar(10) NOT NULL
);

CREATE TABLE ticket(
 ID int PRIMARY KEY AUTO_INCREMENT,
 PARKING_NUMBER int NOT NULL,
 VEHICLE_REG_NUMBER varchar(10) NOT NULL,
 PRICE double,
 IN_TIME DATETIME NOT NULL,
 OUT_TIME DATETIME,
 FOREIGN KEY (PARKING_NUMBER)
 REFERENCES parking(PARKING_NUMBER));

INSERT INTO parking(PARKING_NUMBER,AVAILABLE,TYPE) VALUES(1,true,'CAR');
INSERT INTO parking(PARKING_NUMBER,AVAILABLE,TYPE) VALUES(2,true,'CAR');
INSERT INTO parking(PARKING_NUMBER,AVAILABLE,TYPE) VALUES(3,true,'CAR');
INSERT INTO parking(PARKING_NUMBER,AVAILABLE,TYPE) VALUES(4,true,'BIKE');
INSERT INTO parking(PARKING_NUMBER,AVAILABLE,TYPE) VALUES(5,true,'BIKE');

ALTER TABLE ticket ADD COLUMN discount TINYINT(1) DEFAULT 0;
commit;